http:
  routers:
    frontend-router:
      rule: "Host(`localhost`) && PathPrefix(`/`)"
      service: frontend-service
      priority: 1
      
    backend-admin-router:
      rule: "Host(`localhost`) && PathPrefix(`/admin`)"
      service: backend-service
      priority: 10
      
    forum-router:
      rule: "Host(`localhost`) && PathPrefix(`/forum`)"
      service: forum-service
      priority: 5

  services:
    frontend-service:
      loadBalancer:
        servers:
          - url: "http://frontend:8000"
          
    backend-service:
      loadBalancer:
        servers:
          - url: "http://backend:1337"
          
    forum-service:
      loadBalancer:
        servers:
          - url: "http://forum:4567"