api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
    network: web

certificatesResolvers:
  letsencrypt:
    acme:
      email: example@example.com
      storage: /ssl-certs/acme.json
      httpChallenge:
        entryPoint: web

global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: INFO

accessLog: {}

tls:
  options:
    default:
      minVersion: "VersionTLS12"
  stores:
    default:
      defaultCertificate:
        certFile: /ssl-certs/cert.crt
        keyFile: /ssl-certs/cert.key

http:
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true